# pyright: reportUnknownArgumentType=false
# ^ Alembic's generated op.create_table() calls pass postgresql.ENUM columns pyright cannot type.
"""identity

Revision ID: 0001
Revises:
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Extensions & Enums
    op.execute("create extension if not exists vector;")
    op.execute("create extension if not exists pgcrypto;")
    op.execute("create extension if not exists citext;")

    op.execute("create type tenant_status as enum ('active', 'inactive');")
    op.execute("create type member_role as enum ('owner', 'admin', 'editor');")
    op.execute("create type operator_role as enum ('admin', 'member');")
    op.execute("create type invitation_kind as enum ('tenant_member', 'operator');")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM("active", "inactive", name="tenant_status", create_type=False),
            server_default="active",
            nullable=False,
        ),
        sa.Column("brand_color", sa.Text(), nullable=True),
        sa.Column("brand_logo_key", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenants")),
        sa.UniqueConstraint("slug", name=op.f("uq_tenants_slug")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=True),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("is_staff", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("totp_secret_enc", sa.LargeBinary(), nullable=True),
        sa.Column("totp_enabled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("entity", sa.Text(), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("ip_hash", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], name=op.f("fk_audit_events_actor_id_users")),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], name=op.f("fk_audit_events_tenant_id_tenants")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(
        "ix_audit_events_tenant_id_created_at",
        "audit_events",
        ["tenant_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "operator_orgs",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], name=op.f("fk_operator_orgs_created_by_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operator_orgs")),
    )
    op.create_table(
        "password_reset_tokens",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_password_reset_tokens_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_password_reset_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_password_reset_tokens_token_hash")),
    )
    op.create_index(op.f("ix_password_reset_tokens_user_id"), "password_reset_tokens", ["user_id"], unique=False)
    op.create_table(
        "sessions",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(), nullable=False),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fresh_auth_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("mfa_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_sessions_token_hash")),
    )
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_table(
        "tenant_members",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role", postgresql.ENUM("owner", "admin", "editor", name="member_role", create_type=False), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_tenant_members_tenant_id_tenants"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_tenant_members_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("tenant_id", "user_id", name=op.f("pk_tenant_members")),
    )
    op.create_index(op.f("ix_tenant_members_user_id"), "tenant_members", ["user_id"], unique=False)
    op.create_table(
        "invitations",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            postgresql.ENUM("tenant_member", "operator", name="invitation_kind", create_type=False),
            nullable=False,
        ),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column(
            "role", postgresql.ENUM("owner", "admin", "editor", name="member_role", create_type=False), nullable=True
        ),
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column("operator_org_id", sa.Uuid(), nullable=True),
        sa.Column("token_hash", sa.LargeBinary(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepted_by", sa.Uuid(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invited_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "(kind = 'tenant_member' AND role IS NOT NULL AND operator_org_id IS NULL) OR "
            "(kind = 'operator' AND role IS NULL AND operator_org_id IS NOT NULL AND customer_id IS NOT NULL)",
            name=op.f("ck_invitations_kind_fields"),
        ),
        sa.ForeignKeyConstraint(["accepted_by"], ["users.id"], name=op.f("fk_invitations_accepted_by_users")),
        sa.ForeignKeyConstraint(["invited_by"], ["users.id"], name=op.f("fk_invitations_invited_by_users")),
        sa.ForeignKeyConstraint(
            ["operator_org_id"], ["operator_orgs.id"], name=op.f("fk_invitations_operator_org_id_operator_orgs")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_invitations_tenant_id_tenants"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invitations")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_invitations_token_hash")),
    )
    op.create_index(op.f("ix_invitations_tenant_id"), "invitations", ["tenant_id"], unique=False)
    op.create_table(
        "operator_members",
        sa.Column("operator_org_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            postgresql.ENUM("admin", "member", name="operator_role", create_type=False),
            server_default="member",
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["operator_org_id"],
            ["operator_orgs.id"],
            name=op.f("fk_operator_members_operator_org_id_operator_orgs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_operator_members_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("operator_org_id", "user_id", name=op.f("pk_operator_members")),
    )
    # ### end Alembic commands ###

    # Roles and RLS
    op.execute("alter table tenants enable row level security;")
    op.execute("alter table tenants force row level security;")
    op.execute(
        "create policy p_tenants_tenant on tenants "
        "using (id = nullif(current_setting('app.tenant_id', true), '')::uuid);"
    )
    # Tenants are created and deactivated by staff through the admin engine; members only read and edit branding.
    op.execute("grant select, update on tenants to seedoc_app;")

    for table in ["tenant_members", "invitations", "audit_events"]:
        op.execute(f"alter table {table} enable row level security;")
        op.execute(f"alter table {table} force row level security;")
        op.execute(
            f"create policy p_{table}_tenant on {table} "
            "using (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid) "
            "with check (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);"
        )

    # Global events (tenant_id null, e.g. auth.login_failed) may be inserted by the app but never read back by it.
    op.execute(
        "create policy p_audit_events_global on audit_events for insert to seedoc_app with check (tenant_id is null);"
    )
    op.execute("grant select, insert on audit_events to seedoc_app;")
    op.execute("grant select, insert, update, delete on tenant_members to seedoc_app;")
    op.execute("grant select, insert, update, delete on invitations to seedoc_app;")

    for table in ["users", "sessions", "password_reset_tokens", "operator_orgs", "operator_members"]:
        op.execute(f"grant select, insert, update, delete on {table} to seedoc_app;")

    op.execute("""
create or replace function member_tenants(p_user_id uuid)
returns table (tenant_id uuid, tenant_name text, role member_role)
security definer
set search_path = public
language sql
as $$
  select t.id as tenant_id, t.name as tenant_name, tm.role
  from tenants t
  join tenant_members tm on tm.tenant_id = t.id
  where tm.user_id = p_user_id;
$$;
""")

    # Auth needs the invitation's tenant before any tenant is set; the caller then reads the row under RLS.
    op.execute("""
create or replace function resolve_invitation(p_token_hash bytea)
returns table (invitation_id uuid, tenant_id uuid)
security definer
set search_path = public
language sql
stable
as $$
  select i.id, i.tenant_id from invitations i where i.token_hash = p_token_hash;
$$;
""")
    op.execute("revoke all on function resolve_invitation(bytea) from public;")
    op.execute("grant execute on function resolve_invitation(bytea) to seedoc_app;")


def downgrade() -> None:
    op.execute("drop function if exists resolve_invitation;")
    op.execute("drop function if exists member_tenants;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("operator_members")
    op.drop_index(op.f("ix_invitations_tenant_id"), table_name="invitations")
    op.drop_table("invitations")
    op.drop_index(op.f("ix_tenant_members_user_id"), table_name="tenant_members")
    op.drop_table("tenant_members")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_password_reset_tokens_user_id"), table_name="password_reset_tokens")
    op.drop_table("password_reset_tokens")
    op.drop_table("operator_orgs")
    op.drop_index("ix_audit_events_tenant_id_created_at", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_table("users")
    op.drop_table("tenants")
    # ### end Alembic commands ###
    op.execute("drop type if exists invitation_kind;")
    op.execute("drop type if exists operator_role;")
    op.execute("drop type if exists member_role;")
    op.execute("drop type if exists tenant_status;")
