#!/usr/bin/env bash
# One-time (idempotent) setup of the staging server (ROADMAP M0-A9). Run as root:
#   ssh root@<server> 'bash -s' < infra/staging/provision.sh
# Installs Docker, adds a 2 GB swap file, creates the `deploy` user (SSH keys copied from root), locks SSH down to
# keys only, limits Docker log size and creates /opt/seedoc with a generated .env (secrets never leave the server).
set -euo pipefail

APP_DIR=/opt/seedoc
DEPLOY_USER=deploy

export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq docker.io docker-compose-v2 docker-buildx unattended-upgrades openssl >/dev/null

# Docker: keep container logs small (json-file default grows without limit).
install -d /etc/docker
cat >/etc/docker/daemon.json <<'JSON'
{ "log-driver": "json-file", "log-opts": { "max-size": "10m", "max-file": "3" } }
JSON
systemctl enable --now docker >/dev/null
systemctl restart docker

# Swap: 4 GB RAM is tight for Postgres + API + image loads.
if ! swapon --show | grep -q /swapfile; then
  fallocate -l 2G /swapfile
  chmod 600 /swapfile
  mkswap /swapfile >/dev/null
  swapon /swapfile
  grep -q '^/swapfile' /etc/fstab || echo '/swapfile none swap sw 0 0' >>/etc/fstab
fi

# Deploy user: runs docker compose; gets root's authorized keys (Raven) — the CI key is added separately.
if ! id "$DEPLOY_USER" >/dev/null 2>&1; then
  useradd --create-home --shell /bin/bash "$DEPLOY_USER"
fi
usermod -aG docker "$DEPLOY_USER"
install -d -m 700 -o "$DEPLOY_USER" -g "$DEPLOY_USER" "/home/$DEPLOY_USER/.ssh"
touch "/home/$DEPLOY_USER/.ssh/authorized_keys"
while read -r key; do
  [ -n "$key" ] && ! grep -qxF "$key" "/home/$DEPLOY_USER/.ssh/authorized_keys" && echo "$key" >>"/home/$DEPLOY_USER/.ssh/authorized_keys"
done </root/.ssh/authorized_keys
chown "$DEPLOY_USER:$DEPLOY_USER" "/home/$DEPLOY_USER/.ssh/authorized_keys"
chmod 600 "/home/$DEPLOY_USER/.ssh/authorized_keys"

# SSH: keys only. Root keeps key login for emergencies.
cat >/etc/ssh/sshd_config.d/10-seedoc.conf <<'CONF'
PasswordAuthentication no
KbdInteractiveAuthentication no
PermitRootLogin prohibit-password
CONF
systemctl reload ssh

# App directory + secrets. Generated once; never overwritten. Values marked FILL_IN come from the password vault.
install -d -m 750 -o "$DEPLOY_USER" -g "$DEPLOY_USER" "$APP_DIR"
if [ ! -f "$APP_DIR/.env" ]; then
  secret() { openssl rand -base64 32; }
  password() { openssl rand -hex 24; }
  owner_pw=$(password) app_pw=$(password) admin_pw=$(password)
  umask 077
  cat >"$APP_DIR/.env" <<ENV
# SeeDoc staging — generated by infra/staging/provision.sh on $(date -u +%F). Never commit, never paste in chat.
# Lines marked FILL_IN: copy the value from the password vault (ssh deploy@<server>, then: nano $APP_DIR/.env).
ENVIRONMENT=staging
APP_URL=https://staging.seedoc.cloud
APP_HOST=staging.seedoc.cloud

POSTGRES_PASSWORD=$(password)
SEEDOC_OWNER_PASSWORD=$owner_pw
SEEDOC_APP_PASSWORD=$app_pw
SEEDOC_ADMIN_PASSWORD=$admin_pw
DATABASE_URL=postgresql+asyncpg://seedoc_app:$app_pw@postgres:5432/seedoc
DATABASE_ADMIN_URL=postgresql+asyncpg://seedoc_admin:$admin_pw@postgres:5432/seedoc
DATABASE_OWNER_URL=postgresql+asyncpg://seedoc_owner:$owner_pw@postgres:5432/seedoc

PIN_ENCRYPTION_KEY=$(secret)
TOTP_ENCRYPTION_KEY=$(secret)
IP_HASH_PEPPER=$(secret)

# Hetzner Object Storage (bucket seedoc-staging, NBG1)
S3_ENDPOINT=https://nbg1.your-objectstorage.com
S3_REGION=nbg1
S3_BUCKET=seedoc-staging
S3_ACCESS_KEY=FILL_IN
S3_SECRET_KEY=FILL_IN

# Resend over SMTP (ARCHITECTURE D20)
MAIL_SMTP_HOST=smtp.resend.com
MAIL_SMTP_PORT=2465
MAIL_SMTP_USER=resend
MAIL_API_KEY=FILL_IN
MAIL_FROM=SeeDoc <noreply@mail.seedoc.cloud>

# Optional on staging (required in production): AI from M4, Sentry later
AI_API_KEY=
SENTRY_DSN=
ENV
  chown "$DEPLOY_USER:$DEPLOY_USER" "$APP_DIR/.env"
  chmod 600 "$APP_DIR/.env"
  echo "created $APP_DIR/.env — fill in the FILL_IN values from the vault"
else
  echo "$APP_DIR/.env exists — left unchanged"
fi

echo "provision done: $(docker --version), $(docker compose version | head -1)"
